-- Scanner Test, Dont compile

-
+
"string"
<
>
*
/
//
~
#
..
<
<=
>
>=
==
~=

"Ahoj\n\"Sve'te \\\034"

function reads() : string
function readi() : integer
function readn() : number

function main() -- uzivatelska funkce bez parametru
-- comment

--[[
block
line1
line2
]]--

id_a
12.12

and
boolean
do
end
else
elseif
false
function
integer
if
nil
not
number
or
string
require
return
then
true
while
