-- Scanner Test, Dont compile

-
+
<
>
*
/
//
%
^
~
#
"string"
;
:
,
..
<
<=
>
>=
==
~=

"Ahoj svìte"
""
"\n \t \" \\"
"\110"
"Ahoj\n\"Sve'te \\\034"

function reads() : string
function readi() : integer
function readn() : number

function main() -- uzivatelska funkce bez parametru
-- comment

--[[
block
line1
line2
]]--

id_a
12.12
1e3
1e-3
1e+3
1.3e3

and
boolean
do
end
else
elseif
false
function
integer
if
nil
not
number
or
string
require
return
then
true
while